title: The IMERSIVE Research Group
description: "Innovative Modeling for Environmental & Real-time Statistics: Inference, Visualization & Exploration | IME-USP"
theme: minima

# Opções de navegação do menu
header_pages:
  - index.md
  - people.md
  - research.md
  - software.md
  - contact.md
